# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8faa8492ad80d4791fb7d10d57b6033bcc206c1e7d243c0be0bd1ff424f0a87d38dce2a458dfd2e64bebe89cdb5f5aa196368e7762929699346ff8904869dc43

  
test:
  secret_key_base: e47ce4cbab3c67a864485f5d30d4666b95f00a2a097ceff6228840a4b8382057f7a93f20dd141e926b3a92b20ad39f05084e61988d5b36cd030791d0d7ae42ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
